// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv0BTzPUcNxecBRAWrIinxjeacDGlFGvY',
    appId: '1:665343633304:web:7990fd0d3429cc0d01aded',
    messagingSenderId: '665343633304',
    projectId: 'sistemacorrespondencia-3fbba',
    authDomain: 'sistemacorrespondencia-3fbba.firebaseapp.com',
    storageBucket: 'sistemacorrespondencia-3fbba.firebasestorage.app',
    measurementId: 'G-K3N3VXSH36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ1UEOzv43rtcrUI8x6PQZoI-HcdLEPSs',
    appId: '1:665343633304:android:7e24a6ad5b7f5be401aded',
    messagingSenderId: '665343633304',
    projectId: 'sistemacorrespondencia-3fbba',
    storageBucket: 'sistemacorrespondencia-3fbba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgKk3TKH84xY9mgHJChAToX-QFzo-fk-Q',
    appId: '1:665343633304:ios:b2c4c1dcde288a4801aded',
    messagingSenderId: '665343633304',
    projectId: 'sistemacorrespondencia-3fbba',
    storageBucket: 'sistemacorrespondencia-3fbba.firebasestorage.app',
    iosBundleId: 'com.example.sistemaCorrespondenciaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgKk3TKH84xY9mgHJChAToX-QFzo-fk-Q',
    appId: '1:665343633304:ios:b2c4c1dcde288a4801aded',
    messagingSenderId: '665343633304',
    projectId: 'sistemacorrespondencia-3fbba',
    storageBucket: 'sistemacorrespondencia-3fbba.firebasestorage.app',
    iosBundleId: 'com.example.sistemaCorrespondenciaf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv0BTzPUcNxecBRAWrIinxjeacDGlFGvY',
    appId: '1:665343633304:web:d384d035a168d64d01aded',
    messagingSenderId: '665343633304',
    projectId: 'sistemacorrespondencia-3fbba',
    authDomain: 'sistemacorrespondencia-3fbba.firebaseapp.com',
    storageBucket: 'sistemacorrespondencia-3fbba.firebasestorage.app',
    measurementId: 'G-7WQNTE6R56',
  );
}
